branches:
  only:
    - master
    - develop

environment:
  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"
  PYTHON: "C:\\Python35"
  dotnetcore_version: 2.1.302
  nodejs_version: "8"

build_script:
  - ps: |
      echo "appveyor:"+$pwd
      ./ps/e2etest.ps1
  